---

# TODO: Split this out into separate handler files, once https://github.com/ansible/ansible/issues/13485 is resolved.


- name: Restart Finder
  command: killall Finder

- name: Reload QuickLook daemon
  command: qlmanage -r

- name: Restart Launch Services
  command: /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/LaunchServices.framework/Versions/A/Support/lsregister -kill -r -domain local -domain system -domain user
