---

## Configure Finder the way we want it.
## Note that some of these settings also affect File Open and Save dialogs.

## CREDITS:
##   Many of these settings come from https://github.com/mathiasbynens/dotfiles/blob/master/.osx.


- debug:
    msg: Configuring Mac Finder

- name: Show all files in Finder
  osx_defaults:
    domain: com.apple.finder
    key: AppleShowAllFiles
    value: TRUE
    type: bool
  notify:
    - Restart Finder

- name: Show file extensions in Finder
  osx_defaults:
    domain: NSGlobalDomain
    key: AppleShowAllExtensions
    value: TRUE
    type: bool
  notify:
    - Restart Finder

- name: Don't warn about changing a file extension in Finder
  osx_defaults:
    domain: com.apple.finder
    key: FXEnableExtensionChangeWarning
    value: FALSE
    type: bool
  notify:
    - Restart Finder

# Other view modes: 'icnv', 'clmv', 'Flwv'.
- name: Use list view in all Finder windows by default
  osx_defaults:
    domain: com.apple.finder
    key: FXPreferredViewStyle
    value: Nlsv
    type: string
  notify:
    - Restart Finder

- name: Show folders before files in Finder
  osx_defaults:
    domain: com.apple.finder
    key: _FXSortFoldersFirst
    value: 1
    type: int
  notify:
    - Restart Finder

- name: When opening a new Finder window, start in the home directory
  osx_defaults:
    domain: com.apple.finder
    key: NewWindowTargetPath
    value: "file://{{ ansible_env.HOME }}"
  notify:
    - Restart Finder

- name: Display full path in Finder window titles
  osx_defaults:
    domain: com.apple.finder
    key: _FXShowPosixPathInTitle
    value: TRUE
    type: bool
  notify:
    - Restart Finder

- name: Show Path Bar in Finder windows
  osx_defaults:
    domain: com.apple.finder
    key: ShowPathbar
    value: TRUE
    type: bool
  notify:
    - Restart Finder

- name: Show Status Bar in Finder windows
  osx_defaults:
    domain: com.apple.finder
    key: ShowStatusBar
    value: TRUE
    type: bool
  notify:
    - Restart Finder

- name: Show Tab Bar in Finder windows
  osx_defaults:
    domain: com.apple.finder
    key: ShowTabView
    value: TRUE
    type: bool
  notify:
    - Restart Finder

- name: Allow quitting Finder
  osx_defaults:
    domain: com.apple.finder
    key: QuitMenuItem
    value: TRUE
    type: bool
  notify:
    - Restart Finder

- name: Disable animations in Finder
  osx_defaults:
    domain: com.apple.finder
    key: DisableAllAnimations
    value: TRUE
    type: bool
  notify:
    - Restart Finder

- name: Disable animations when opening a QuickLook window
  osx_defaults:
    domain: NSGlobalDomain
    key: QLPanelAnimationDuration
    value: 0
    type: float
  notify:
    - Restart Finder

- name: Warn before emptying the Trash
  osx_defaults:
    domain: com.apple.finder
    key: WarnOnEmptyTrash
    value: TRUE
    type: bool
  notify:
    - Restart Finder

- name: Empty Trash securely by default
  osx_defaults:
    domain: com.apple.finder
    key: EmptyTrashSecurely
    value: TRUE
    type: bool
  notify:
    - Restart Finder

- name: Don't hide the ~/Library folder
  command: chflags nohidden ~/Library
  notify:
    - Restart Finder

- name: Enable spring loading effect for directories
  osx_defaults:
    domain: NSGlobalDomain
    key: com.apple.springing.enabled
    value: TRUE
    type: bool
  notify:
    - Restart Finder

- name: Spring loading effect should proceed without delay
  osx_defaults:
    domain: NSGlobalDomain
    key: com.apple.springing.delay
    value: 0
    type: float
  notify:
    - Restart Finder

- name: Show sidebar in Finder
  osx_defaults:
    domain: com.apple.finder
    key: ShowSidebar
    value: TRUE
    type: bool
  notify:
    - Restart Finder

- name: Set sidebar icons to medium size
  osx_defaults:
    domain: NSGlobalDomain
    key: NSTableViewDefaultSizeMode
    value: 2
    type: int
  notify:
    - Restart Finder

- name: Hide tags section in Finder sidebar
  osx_defaults:
    domain: com.apple.finder
    key: ShowRecentTags
    value: FALSE
    type: bool
  notify:
    - Restart Finder

- name: Install mysides utility
  homebrew:
    name: mysides

- name: Determine Finder sidebar favorites
  shell: mysides list | awk '{ print $1 }'
  register: current_sidebar_favorites
  changed_when: FALSE

- name: Remove existing sidebar favorites if the current list doesn't match what we want
  command: mysides remove '{{ item }}'
  with_items: "{{ current_sidebar_favorites.stdout_lines }}"
  when: current_sidebar_favorites.stdout_lines | replace('/Users/', '') != (sidebar_favorites | map(attribute='label') | list | replace('Home', ansible_env.HOME) | replace('/Users/', ''))

- name: Set Finder sidebar favorites
  command: mysides add '{{ item.label }}' '{{ item.url }}'
  with_items: "{{ sidebar_favorites }}"
  when: current_sidebar_favorites.stdout_lines | replace('/Users/', '') != (sidebar_favorites | map(attribute='label') | list | replace('Home', ansible_env.HOME) | replace('/Users/', ''))
  notify:
    - Restart Finder
