---

- name: Default to plain text emails in Mac Mail
  osx_defaults:
    domain: com.apple.mail
    key: PreferPlainText
    value: TRUE
    type: bool

- name: Disable animations in Mac Mail
  osx_defaults:
    domain: com.apple.mail
    key: "{{ item }}"
    value: TRUE
    type: bool
  with_items:
    - DisableReplyAnimations
    - DisableSendAnimations

- name: Install Thunderbird
  homebrew_cask:
    name: thunderbird

- include: add_to_dock.yml
  vars:
    name: Thunderbird
    path: /Applications/Thunderbird.app
    after: Calendar
