---


- debug:
    msg: Configuring Mac

- include: prerequisites.yml
  tags: always
- include: hostname.yml
  tags: hostname
- include: homebrew.yml
  tags: homebrew
- include: appstore.yml
  tags: appstore
- include: display.yml
  tags: display
- include: ui.yml
  tags: ui
- include: desktop.yml
  tags: desktop
- include: finder.yml
  tags: finder
- include: dock.yml
  tags: dock
- include: trackpad.yml
  tags: trackpad
- include: keyboard.yml
  tags: keyboard
- include: terminal.yml
  tags: terminal
- include: utilities.yml
  tags: utilities
- include: menubar.yml
  tags: menubar
- include: bash.yml
  tags: bash
- include: quicklook.yml
  tags: quicklook
- include: mail.yml
  tags: mail
- include: fonts.yml
  tags: fonts
- include: web.yml
  tags: web, browser, browsers
