---

- name: Install Atom editor
  homebrew_cask:
    name: atom

- name: Add Atom icon to Dock
  include: add_to_dock.yml
  vars:
    name: Atom
    path: /Applications/Atom.app
    after: Terminal

- name: Install Atom plugins to modify UI
  command: "apm install {{ item }}"
  args:
    creates: "{{ ansible_env.HOME }}/.atom/packages/{{ item }}"
  with_items:
    - unity-ui
    - soda-light-ui
    - solarized-light-syntax-modified
    - base16-light-syntax
    - fonts

- name: Install some miscellaneous Atom plugins
  command: "apm install {{ item }}"
  args:
    creates: "{{ ansible_env.HOME }}/.atom/packages/{{ item }}"
  with_items:
    - highlight-line
    - trailing-spaces
    - semanticolor
    - atom-beautify
    - pretty-json
    - auto-indent
    - autocomplete-plus
    - autocomplete-paths
    - autocomplete-snippets
    - autocomplete-ctags
    - bracket-matcher
    - sort-lines
    - wordcount
    - open-recent
    - file-icons  # I like seti-icons a bit better, but this has more icons and a default icon.
    - atom-pair
    - tag
    - platformio-ide-terminal
    - print-code
    - change-case
    - atom-transpose
    - copy-path
    - local-history
    - sublime-style-column-selection  # Option+drag to select a rectangular area.
    - touch-bar-utility

- name: Install Atom plugins for minimap
  command: "apm install {{ item }}"
  args:
    creates: "{{ ansible_env.HOME }}/.atom/packages/{{ item }}"
  with_items:
    - minimap
    - minimap-autohide
    - minimap-selection
    - minimap-pigments
    - minimap-find-and-replace
    - minimap-git-diff
    - minimap-highlight-selected

- name: Install Atom plugins for git
  command: "apm install {{ item }}"
  args:
    creates: "{{ ansible_env.HOME }}/.atom/packages/{{ item }}"
  with_items:
    - git-log
    - git-blame
    - tree-view-git-status

- name: Install Atom plugins for jumping to definitions
  command: "apm install {{ item }}"
  args:
    creates: "{{ ansible_env.HOME }}/.atom/packages/{{ item }}"
  with_items:
    - goto-definition
    - hyperclick # Used by Elmjutsu.

- name: Install Atom plugins for HTML, CSS, and XML
  command: "apm install {{ item }}"
  args:
    creates: "{{ ansible_env.HOME }}/.atom/packages/{{ item }}"
  with_items:
    - autoclose-html
    - autocomplete-html
    - language-sass
    - linter-tidy
    - linter-csslint
    - linter-xmllint
    - xml-formatter
    - pigments
    - color-picker
    - sass-autocompile
    - atom-wrap-in-tag

- name: Install Atom plugins for Ruby
  command: "apm install {{ item }}"
  args:
    creates: "{{ ansible_env.HOME }}/.atom/packages/{{ item }}"
  with_items:
    - autocomplete-ruby
    - ruby-test
    - ruby-block
    - linter-rubocop
    - rails-snippets
    - rspec-snippets
    - language-gherkin
    - capybara-snippets
    - language-rspec
    - language-slim
    - linter-slim
    - html2slim
    - language-haml
    - html2haml
    - ruby-test
    - rails-transporter
    - rails-model-schema

- name: Install Atom plugins for JavaScript
  command: "apm install {{ item }}"
  args:
    creates: "{{ ansible_env.HOME }}/.atom/packages/{{ item }}"
  with_items:
    - linter-eslint
    - language-javascript-jsx
    - language-javascript-semantic
    - javascript-snippets
    - linter-coffeelint
    - prettier-atom
    - autocomplete-modules

- name: Install Atom plugins for Crystal
  command: "apm install {{ item }}"
  args:
    creates: "{{ ansible_env.HOME }}/.atom/packages/{{ item }}"
  with_items:
    - ide-crystal
    - crystal-block

- name: Install Atom plugins for Elm
  command: "apm install {{ item }}"
  args:
    creates: "{{ ansible_env.HOME }}/.atom/packages/{{ item }}"
  with_items:
    - language-elm
    - linter-elm-make
    - elmjutsu

- name: Install Atom plugins for Java
  command: "apm install {{ item }}"
  args:
    creates: "{{ ansible_env.HOME }}/.atom/packages/{{ item }}"
  with_items:
    - language-java # Should be built in, but doesn't hurt to be explicit.
    - autocomplete-java
    - linter-javac
    - java-generator

- name: Install Atom plugins for Groovy (and Grails)
  command: "apm install {{ item }}"
  args:
    creates: "{{ ansible_env.HOME }}/.atom/packages/{{ item }}"
  with_items:
    - language-groovy
    - atom-grails

- name: Install Atom plugins for Ansible
  command: "apm install {{ item }}"
  args:
    creates: "{{ ansible_env.HOME }}/.atom/packages/{{ item }}"
  with_items:
    - language-ansible
    - language-terraform

- name: Install Atom plugins for Racket
  command: "apm install {{ item }}"
  args:
    creates: "{{ ansible_env.HOME }}/.atom/packages/{{ item }}"
  with_items:
    - language-racket

- name: Install Bash completion for APM (Atom Package Manager)
  homebrew:
    name: apm-bash-completion

- name: Determine current default app for Markdown files
  shell: duti -x md | tail -1
  register: markdown_editor
  changed_when: FALSE

- name: Set Atom as the default editor for Markdown files
  command: duti -s com.github.atom {{ item }} editor
  when: markdown_editor.stdout != "com.thoughtbot.Markoff"
  with_items:
    - net.daringfireball.markdown
    - ".md"
  notify:
    - Restart Launch Services
