---

- debug:
    msg: Installing software development tools


- name: Install Homebrew version of git, to get new features
  homebrew:
    name: git

- include: misc.yml
  tags: misc
- include: atom.yml
  tags: atom
- include: emacs.yml
  tags: emacs
- include: web.yml
  tags: web
- include: postgresql.yml
  tags: [postgresql, postgres]
- include: ruby.yml
  tags: ruby
- include: perl.yml
  tags: perl
- include: java.yml
  tags: java, jdk
- include: javascript.yml
  tags: [javascript, node]
- include: elm.yml
  tags: elm
- include: racket.yml
  tags: racket
- include: nim.yml
  tags: nim
- include: pony.yml
  tags: pony
- include: haskell.yml
  tags: haskell
- include: lua.yml
  tags: lua
- include: llvm.yml
  tags: llvm
- include: devops.yml
  tags: devops
